### ISSUE TITLE
Crashes when using include_chats

### ISSUE THREAD

**Issue by Rayanfer32** [odysseusmax/tg-index#17]
![image](https://user-images.githubusercontent.com/37145078/93738535-a6b1e800-fc03-11ea-90a0-10f20327bf6c.png)
```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/tgi/app/__main__.py", line 12, in <module>
    Indexer().run()
  File "/home/runner/tgi/app/main.py", line 46, in run
    self.loop.run_until_complete(self.startup())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/tgi/app/main.py", line 32, in startup
    await setup_routes(self.server, Views(self.tg_client))
  File "/home/runner/tgi/app/routes.py", line 73, in setup_routes
    chat = await client.get_entity(chat_id)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/client/users.py", line 268, in get_entity
    inputs.append(await self.get_input_entity(x))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/client/users.py", line 442, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7faa5172a1f0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
```

**Comment by odysseusmax** [comment]
Set the chat id correctly, include `-` alse, if any.

**Comment by Rayanfer32** [comment]
![photo_2020-09-21_12-23-10](https://user-images.githubusercontent.com/37145078/93739164-402dc980-fc05-11ea-9554-a78c7ef487f9.jpg)
![image](https://user-images.githubusercontent.com/37145078/93739200-59367a80-fc05-11ea-987c-e949691ece96.png)

**Comment by Rayanfer32** [comment]
Still it is crashing with the same error

**Comment by rking32** [comment]
@Rayanfer32 try `"include_chats": [-1001282848973]`

**Comment by Rayanfer32** [comment]
> @Rayanfer32 try `"include_chats": [-1001282848973]`

Thanks Dude it worked!😍
