### ISSUE TITLE
bool object is not subscriptable

### ISSUE THREAD

**Issue by spinnaker1** [odysseusmax/tg-index#32]
I get this error when running the app.

**Comment by rayanfer32** [comment]
Please post the entire traceback log of the error here... 

> I get this error when running the app.

**Comment by spinnaker1** [comment]
@rayanfer32 
```
user@ubuntu:~/tg-index$ python3 -m app
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/tg-index/app/__main__.py", line 12, in <module>
    Indexer().run()
  File "/home/user/tg-index/app/main.py", line 64, in run
    self.loop.run_until_complete(self.startup())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/tg-index/app/main.py", line 52, in startup
    await setup_routes(self.server, Views(self.tg_client))
  File "/home/user/tg-index/app/routes.py", line 13, in setup_routes
    index_all = index_settings["index_all"]
TypeError: 'bool' object is not subscriptable
```

**Comment by spinnaker1** [comment]
Sorry, I didnt used the index_settings json variable correctly. Solved.
