### ISSUE TITLE
Error when using single source.

### ISSUE THREAD

**Issue by pseudokawaii** [odysseusmax/tg-index#34]
`INDEX_SETTINGS` used :
```
{
    "index_all": false,
    "index_private": false,
    "index_group": false,
    "index_channel": true,
    "exclude_chats": [],
    "include_chats": [
        -12345678910
    ],
    "otg": {
        "enable": false,
        "include_private": true,
        "include_group": false,
        "include_channel": true
    }
}
```
Error output :
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/runner/culturecloud/app/views/middlewhere.py", line 50, in factory
    return await handler(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp_jinja2/__init__.py", line 227, in wrapped
    context = await coro(*args)
  File "/home/runner/culturecloud/app/views/home_view.py", line 9, in home
    raise web.HTTPFound(f"{self.chat_ids[0]['alias_id']}")
KeyError: 0
```

**Comment by odysseusmax** [comment]
fixed it in the latest update
