### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by pseudokawaii** [odysseusmax/tg-index#38]
From a Repl.it deployment ~
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/home/runner/tg-index/app/views/middlewhere.py", line 76, in factory
    return await handler(request)
  File "/home/runner/tg-index/app/views/logo_view.py", line 35, in logo
    font = ImageFont.truetype("arial.ttf", 50)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/PIL/ImageFont.py", line 853, in truetype
    return freetype(font)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/PIL/ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/PIL/ImageFont.py", line 209, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by odysseusmax** [comment]
download and add `arial.ttf` font file to the project

**Comment by pseudokawaii** [comment]
@odysseusmax where to add it? In the root folder?

**Comment by odysseusmax** [comment]
yes, try it, IG pillow will automatically find it. If not working make a folder `fonts/` and paste it there.

**Comment by pseudokawaii** [comment]
@odysseusmax copied the arial.ttf font file from Windows fonts folder and put it on the root folder of the repo. Issue's gone now.
