### ISSUE TITLE
SESSION_STRING error while deploying replit

### ISSUE THREAD

**Issue by tonyzhub** [odysseusmax/tg-index#57]
Getting SESSION_SRING Error while deploy in replit

 **_python3 -m app**
Traceback (most recent call last):
  File "/home/runner/tg-index/app/config.py", line 38, in <module>
    session_string = os.environ["SESSION_STRING"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SESSION_STRING'_

**Comment by tonyzhub** [comment]
run 
pyhon repl-config/run-repl.py
