### ISSUE TITLE
cannot import name 'Markup' from 'jinja2' 

### ISSUE THREAD

**Issue by Eikosa** [odysseusmax/tg-index#66]
```Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\tg-index\app\__main__.py", line 3, in <module>
    from .main import Indexer
  File "C:\Users\USER\tg-index\app\main.py", line 12, in <module>
    from .routes import setup_routes
  File "C:\Users\USER\tg-index\app\routes.py", line 9, in <module>
    from .views import Views
  File "C:\Users\USER\tg-index\app\views\__init__.py", line 13, in <module>
    from .info_view import InfoView
  File "C:\Users\USER\tg-index\app\views\info_view.py", line 8, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\jinja2\__init__.py)```

**Comment by raihanirfan** [comment]
same

**Comment by ACHIYA96** [comment]
Add the following line to requirements.txt

jinja2==3.0.3

**Comment by Sercalod** [comment]
> Add the following line to requirements.txt
> 
> jinja2==3.0.3

This worked for me. Much appreciated.

**Comment by erickyun** [comment]
> > Add the following line to requirements.txt
> > jinja2==3.0.3
> 
> This worked for me. Much appreciated.

How did you setup env file? 
Can you please tell me how to name the file and how you put variables in that file can you share Screenshot both?
